[package]
name = "coffemachine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.0"
enum-iterator = "0.7.0"
lazy_static = "1.4.0"

[dev-dependencies]
mockall = "0.10.2"